CREATE TABLE users(
id INT(11)NOT NULL, 
username VARCHAR(45)NOT NULL, 
nombre VARCHAR(45)NOT NULL, 
apellido  VARCHAR(45)NOT NULL, 
documento INT(45)NOT NULL);

ALTER TABLE users
    ADD PRIMARY KEY (id);

ALTER TABLE users
    MODIFY id INT(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=1;

CREATE TABLE articulos(
id INT(11)NOT NULL, 
tittle VARCHAR(45)NOT NULL, 
descript TEXT,
hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
users_id INT(11),
CONSTRAINT fk_users_id FOREIGN KEY(users_id)REFERENCES users(id)
);
ALTER TABLE articulos
    ADD PRIMARY KEY (id);

ALTER TABLE articulos
    MODIFY id INT(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=1;